// <auto-generated />
using EFMusicWebApi.Infrastucture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFMusicWebApi.Infrastucture.Migrations
{
    [DbContext(typeof(MusicApiDbContext))]
    [Migration("20251024145312_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicWebApi.App.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = (short)37,
                            Name = "Adele"
                        },
                        new
                        {
                            Id = 2,
                            Age = (short)34,
                            Name = "Travis Scott"
                        },
                        new
                        {
                            Id = 3,
                            Age = (short)48,
                            Name = "Shakira"
                        });
                });

            modelBuilder.Entity("MusicWebApi.App.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumName = "25",
                            Title = "Hello"
                        },
                        new
                        {
                            Id = 2,
                            AlbumName = "Birds in the Trap Sing McKnight",
                            Title = "Goosebumps"
                        },
                        new
                        {
                            Id = 3,
                            AlbumName = "Sale el sol",
                            Title = "Waka Waka"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
